# Generated by Django 4.2.6 on 2023-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_transaction_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hola, estoy usando MiniBizum!'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.TextField(blank=True),
        ),
    ]
