# Generated by Django 4.2.6 on 2023-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_profile_public_key_transaction_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.BinaryField(blank=True),
        ),
    ]
