# Generated by Django 4.2.6 on 2023-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_alter_transaction_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.BinaryField(blank=True),
        ),
    ]
