# Generated by Django 4.2.6 on 2023-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_alter_profile_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.BinaryField(blank=True),
        ),
    ]
