# Generated by Django 4.2.6 on 2023-11-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0009_profile_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_key',
        ),
    ]
