# Generated by Django 4.2.6 on 2023-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0010_remove_profile_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dh_public_key',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_dh_private_key',
            field=models.TextField(default=None),
        ),
    ]
