# Generated by Django 4.2.6 on 2023-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0012_alter_profile_dh_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
